--- #YAML:1.0
name:               SAFT-Simple
version:            1.0.0
abstract:           create simple SAFT-XML encoded archival finding aids
author:
    - Martin Hoppenheit <martin.hoppenheit@brhf.de>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:         0
    strict:       0
    Test::More:   0
    utf8:         0
    version:      0
    warnings:     0
    XML::LibXML:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
